### ISSUE TITLE
需要战友一起干嘛

### ISSUE THREAD

**Issue by 777ki** [man-pages-zh/coreutils-po#1]
需要战友一起玩吗

**Comment by hosiet** [comment]
当然欢迎！

流程也请参考 https://github.com/man-pages-zh/wiki
另外请参考项目来源
https://github.com/intetnet/manpages_zh

梁博琰 notifications@github.com 於 2015年5月14日週四 16:52 寫道：

**Comment by intetnet** [comment]
https://github.com/intetnet/manpages_zh 这个项目我已经转给 manpages-zh 了，在这里：
https://github.com/manpages-zh/manpages_zh
