### ISSUE TITLE
lokalize 版本问题

### ISSUE THREAD

**Issue by hosiet** [man-pages-zh/coreutils-po#4]
我注意到现在翻译中使用的是不同版本的 lokalize。有 1.5 版本，也有 2.0 版本。这样会不会出问题？

例如， https://github.com/man-pages-zh/coreutils-po/commit/413504caead24bb8fca396dba83e09da267db111 可以看出，“**GNU coreutils 的在线帮助： E<lt>http://www.gnu.org/software/coreutils/E<gt>**” 这一行的翻译在不同版本 lokalize 中被不断地修改，这是否是版本不同导致的？

**Comment by da-liii** [comment]
应该是的，貌似和po4a也有关系。所以我不打算编译安装2.0的Lokalize了。commit的时候尽量小心，能避免则避免，不能避免就这样吧。
