### ISSUE TITLE
我想维护一个mount手册页的翻译

### ISSUE THREAD

**Issue by fbigun** [man-pages-zh/coreutils-po#8]
维护一个mount手册页，我应该怎么建立po文件这类的啊

**Comment by hosiet** [comment]
首先确定 mount 手册页的上游维护项目：[The Linux man-pages project](https://www.kernel.org/doc/man-pages/)，然后请了解上游的翻译情况：https://www.kernel.org/doc/man-pages/translations.html

这个上游与 coreutils 不同，coreutils 是通过 help2man 生成手册页的，而这里的手册页是纯手写的，想要转换成易于翻译的 po 文件再变回 man 手册页可能会比较困难。

我们正在尝试建立由手册页到手册页的翻译工具链，不过还没有成型，所以除了从头编写以外，可能暂时没有现成的工具可用。有一个项目可能有所帮助：[po4a](http://po4a.alioth.debian.org/)，看起来可以提取po文件再生成man手册页。

如果需要从头编写，除了手写 roff 文档外，man-pages-zh 里面有可供选用的工具，例如 [ronn](https://github.com/man-pages-zh/ronn)，还有 docbook XSL 等等工具。

（上面所述如果有欠缺，欢迎补充修正）

**Comment by da-liii** [comment]
mount手册页的上游在[utils-linux](https://github.com/karelzak/util-linux

## 如何确定一个手册页的上游（以Debian中mount为例）

```
/usr/share/man
$ dpkg -S /usr/share/man/man8/mount.8.gz
mount: /usr/share/man/man8/mount.8.gz
/usr/share/man
$ apt show mount
Package: mount
Source: util-linux
Version: 2.26.2-6
Essential: yes
Installed-Size: 409 kB
Maintainer: Debian util-linux Maintainers <ah-util-linux@debian.org>
Pre-Depends: libblkid1 (>= 2.17.2), libc6 (>= 2.17), libmount1 (>= 2.25), libselinux1 (>= 2.0.15), libsmartcols1 (>= 2.25)
Suggests: nfs-common (>= 1:1.1.0-13)
Tag: admin::filesystem, hardware::storage, implemented-in::c,
 interface::commandline, role::program, scope::utility
Section: admin
Priority: required
Download-Size: 174 kB
APT-Manual-Installed: yes
APT-Sources: http://mirrors.ustc.edu.cn/debian/ unstable/main amd64 Packages
Description: Tools for mounting and manipulating filesystems
 This package provides the mount(8), umount(8), swapon(8),
 swapoff(8), and losetup(8) commands.
```

第一个命令说明mount的手册页是随mount这个软件包（**Package**）分发的。
第二个命令说明mount这个软件包来自于util-linux这个源代码包（**Source**）

## 如何翻译一个手册页

首先我们以一个源代码包作为一个单位来翻译。因为每一个源代码包都有一个版本号，这样我们就通过git的tag或者branch来管理我们的翻译的版本号。

。。。（@hosiet 看来我们需要更加完善的wiki）

**Comment by hosiet** [comment]
@sadhen 好吧，说的果然有错误……

The Linux Man-pages Project 更像是一个收集整理分发手册页的项目，不过 Debian 对待 `manpages` 软件包的方式可以在 `/usr/share/doc/manpages/README.Debian`看到，仍然采用了拆包的方式。
在 Archlinux 下情况有所不同，不过也可以通过 pacman 查询手册页所属的软件包。

刚才看了一下，po4a 是一个很好的工具，使用 `po4a-gettextize` 和 `po4a-translate`，再配合 `lokalize` 这类专用工具就可以很好地翻译大多数手册页了（奇葩的除外，例如 docbook XML 生成的 git(1)），这也是`coreutils-po`现在采用的方式。我觉得应当把整体流程写入 Wiki。

另外，已经弃坑的 [LCTT/man-pages](https://github.com/LCTT/man-pages) 也是采用这种方式翻译的。Wiki 图文并茂，给人感觉很好，也列出了不少翻译规范，值得借鉴。

**Comment by da-liii** [comment]
我正在搞util-linux-po

@hosiet 你编辑一下wiki，把翻译流程写写明白。让 @fbigun 看看，是否比较容易理解。我觉得要吸引一些人加入翻译的话。首要的两项就是
1. 已有成果的展示，凸显项目的意义
2. 清晰的wiki，规则的透明化

**Comment by hosiet** [comment]
OK，不过我要先确认一下流程，你看大体是否正确：

## 建立翻译项目
1. 以上游项目（软件包）为单位，在 man-pages-zh 下面建立 GitHub 项目。例如，coreutils
   的翻译建立一个项目，utils-linux 的翻译建立一个项目，procps-ng 的翻译建立一个项目，等等
2. 从上游特定版本导入 man roff 文档
3. 使用 po4a 工具生成模板，进而整理得到翻译所需的 po 文件（具体方法待整理）
4. 向项目中放入配套的翻译预览和更新、生成脚本，确定术语词汇表，等等

## 参与翻译
1. 在 man-pages-zh 下寻找对应翻译项目
2. 认领项目的翻译部分（使用 issue 或其它方式）
3. Clone 项目至本地，使用如 poedit 或 lokalize 等工具进行翻译，将翻译内容设为待审阅状态（fuzzy）并 commit
4. 本地利用 po4a 工具进行翻译预览与自我检查
5. 如果具有直接推送权限，则推送至主干并等待他人审阅；否则使用 fork+PR 方式等待他人进行审阅后合并至主干
6. 待项目基本翻译完毕（暂时认定为所有文档均可生成翻译文档，即翻译量>80%），考虑将翻译后的手册页文档回馈上游（可能是
   lidaobing/manpages-zh）
   
   ## 维护翻译
7. 对翻译完成的项目，认领维护工作
8. 在上游发布新版本后合并上游修改与已有翻译成果（具体方法待探索）
9. 将修改后的结果提交并反馈上游

On Sun, Jun 7, 2015, 14:02 Darcy Shen notifications@github.com wrote:

我正在搞util-linux-po

@hosiet https://github.com/hosiet 你编辑一下wiki，把翻译流程写写明白。让 @fblgun
看看，是否比较容易理解。我觉得要吸引一些人加入翻译的话。首要的两项就是
1. 已有成果的展示，凸显项目的意义
2. 清晰的wiki，规则的透明化

—
Reply to this email directly or view it on GitHub
https://github.com/man-pages-zh/coreutils-po/issues/8#issuecomment-109700894.<img
src="
https://ci3.googleusercontent.com/proxy/jSuHacwKf6a5aM-jGaIK1lDCPNbs8ylsgfsRviiQFaP3-gbarqoC0SqdV0eSVDINjqoNtpX8fHXmf2jl0Qlt0g3GUTdGQqjbgKz53IsOQencIKRPYVxEVOCi4e4EI9SLKlFHktl5z-s6_y1hukuUVneVGYdnVQ=s0-d-e1-ft#https://github.com/notifications/beacon/AIDYFh9dL8623VF6249pJsIIMYvfNzwRks5oQ9YTgaJpZM4E6rht.gif
">

**Comment by da-liii** [comment]
没有问题

**Comment by fbigun** [comment]
看到了你们的努力，不过wiki上也要详细怎么建立这个翻译的环境吧，不然我又得陷入这个安装环境问题的坑里面了啊。
你们说要新建的这个project，我更新好这个文档po，等以后英文版有更新，我是不是还得从头开始翻译 ？

**Comment by da-liii** [comment]
不会的，大部分已经翻译过的条目都可以复用的

**Comment by da-liii** [comment]
已经建立这个环境了，见 https://github.com/man-pages-zh/util-linux-po

你只要专注于翻译po/mount.8.zh_CN.po这个文件就可以了
使用`./preview mount`可以预览，欢迎fork

有什么别的问题也欢迎在wiki这个repo中的issue中提出来

**Comment by fbigun** [comment]
谢谢，我已经接受到了，感谢你的努力。
安装这个翻译的环境，我需要一些帮助，希望有wiki，系统是deepin。
为了装翻译工具还要去安装个linux系统了，我暂时只是在raspberry pi上用linux，系统还是archlinux。
翻译的速度可能不会是快速的。
